// 列表
export const feedsList = {
  count: 8310,
  list: [
    {
      businessCategory: null,
      cityId: 169,
      cityName: "Boston",
      commentCount: 1,
      complaint: false,
      contentDetails: "Fully functional shredder for sale, one missing wheel, 100RMB.",
      createTime: 1556010818000,
      feedDeletedBy: "NONE",
      feedId: 24994,
      feedStatus: "DEMAND",
      feedType: "COMMERCIAL",
      hubId: 742,
      hubName: "745 Atlantic Ave",
      likeCount: 9,
      mobile: null,
      nickName: null,
      rating: null,
      reportCount: 0,
      tag: null,
      tagComplement: null,
      title: "Commercial title Unit test",
      userId: 1,
      userType: null,
    },
    {
      businessCategory: null,
      cityId: 169,
      cityName: "Boston",
      commentCount: 1,
      complaint: false,
      contentDetails: "Fully functional shredder for sale, one missing wheel, 100RMB.",
      createTime: 1556010818000,
      feedDeletedBy: "NONE",
      feedId: 24994,
      feedStatus: "DEMAND",
      feedType: "COMMERCIAL",
      hubId: 742,
      hubName: "745 Atlantic Ave",
      likeCount: 9,
      mobile: null,
      nickName: null,
      rating: null,
      reportCount: 0,
      tag: null,
      tagComplement: null,
      title: "Commercial title Unit test",
      userId: 1,
      userType: null,
    },
  ]
}
